site_name: QGIS STAC API Browser

repo_url: https://github.com/stac-utils/qgis-stac-plugin
repo_name: GitHub

site_description: QGIS STAC API Browser

site_author: Kartoza

nav:
  - Home: 'index.md'
  - Installation: "installation.md"
  - User Guide: "user-guide.md"
  - Development: "development.md"
  - About: "about.md"
  - Changelog: "changelog.md"
  - Tutorials: "tutorial.md"

plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video

markdown_extensions:
  - pymdownx.snippets:
      base_path: .
  - meta:

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs
  palette:
  - scheme: stac
    toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  - scheme: slate
    toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    accent: cyan
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
